version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app  # Mounts project files, so changes reflect instantly
    ports:
      - "5000:5000"
    environment:
      - ENV=development
    depends_on:
      - db
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
